---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: localstack-aws-svc
service:
  port: "4566"
config:
  SERVICES: "s3,sqs"
  APP_NAME: localstack-aws-svc
  DEBUG: "localstack-aws-svc:*"
  ENV: "{{ env }}"
  KUBIFY_ENV: "{{ env }}"
profiles:
  dev:
    resources:
      requests:
        cpu: 64m
        memory: 64Mi
      limits:
        cpu: 128m
        memory: 128Mi

