---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: kafka-svc
service:
  port: "4566"
config:
  APP_NAME: kafka-svc
  DEBUG: "kafka-svc:*"
  ENV: "{{ env }}"
  KUBIFY_ENV: "{{ env }}"
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-svc:2181"
  ALLOW_PLAINTEXT_LISTENER: "no"
  KAFKA_INTER_BROKER_USER: "kubify"
  KAFKA_INTER_BROKER_PASSWORD: "kubify9000"
  KAFKA_CLIENT_USER: "kubify"
  KAFKA_CLIENT_PASSWORD: "kubify9000"
  KAFKA_ZOOKEEPER_USER: "kubify"
  KAFKA_ZOOKEEPER_PASSWORD: "kubify9000"
  # the ingress controller does TLS
  KAFKA_ZOOKEEPER_PROTOCOL: "PLAINTEXT"
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  # for better logs:
  # KAFKA_CLIENT_USERS: "service-name,service-name,service-name"
  # KAFKA_CLIENT_PASSWORDS: "kubify9000,kubify9000,kubify9000"
profiles:
  dev:
      requests:
        cpu: 64m
        memory: 64Mi
      limits:
        cpu: 128m
        memory: 128Mi
  dev:
    # NOTE: Kafka depends on zookeeper-svc running for auto-scaling things
    scaler:
      minReplicas: 2
      maxReplicas: 4
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 40