---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: zookeeper-svc
service:
  port: "2181"
config:
  APP_NAME: zookeeper-svc
  DEBUG: "zookeeper-svc:*"
  ENV: "{{ env }}"
  KUBIFY_ENV: "{{ env }}"
  # the ingress controller does TLS
  ZOO_TLS_CLIENT_ENABLE: "false"
  ALLOW_ANONYMOUS_LOGIN: "no"
  ZOO_ENABLE_AUTH: "true"
  ZOO_CLIENT_USER: "kubify"
  ZOO_CLIENT_PASSWORD: "kubify9000"
  ZOO_SERVER_USERS: "kubify,kubify2"
  ZOO_SERVER_PASSWORDS: "kubify9000,kubify9001"
profiles:
  dev:
      requests:
        cpu: 64m
        memory: 64Mi
      limits:
        cpu: 128m
        memory: 128Mi
